/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e0e3e5',
        'surface': '#f7f9fb',
        'primary': '#3525cd',
        'secondary': '#712ae2',
        'on-surface': '#191c1e',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#c3c0ff',
        'primary-fixed': '#e2dfff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bbff',
        'secondary-container': '#8a4cfc',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'tertiary-container': '#a44100',
        'tertiary': '#7e3000',
        'on-tertiary': '#ffffff',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface-variant': '#464555',
        'outline': '#777587',
        'outline-variant': '#c7c4d8',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#c3c0ff',
        'surface-tint': '#4d44e3',
      },
      fontFamily: {
        'headline': ['Manrope', 'Heebo', 'sans-serif'],
        'body': ['Inter', 'Heebo', 'sans-serif'],
        'label': ['Inter', 'Heebo', 'sans-serif'],
        sans: ['Inter', 'Heebo', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
