import api from './axios';
export const getWorkers = () => api.get('/admin/workers').then(r => r.data);
export const createWorker = (data) => api.post('/admin/workers', data).then(r => r.data);
export const updateWorker = (id, data) => api.put(`/admin/workers/${id}`, data).then(r => r.data);
export const deleteWorker = (id) => api.delete(`/admin/workers/${id}`).then(r => r.data);
export const getWorkerAvailability = (id) => api.get(`/admin/workers/${id}/availability`).then(r => r.data);
export const getServices = () => api.get('/admin/services').then(r => r.data);
export const createService = (data) => api.post('/admin/services', data).then(r => r.data);
export const updateService = (id, data) => api.put(`/admin/services/${id}`, data).then(r => r.data);
export const deleteService = (id) => api.delete(`/admin/services/${id}`).then(r => r.data);
export const getAppointments = (params) => api.get('/admin/appointments', { params }).then(r => r.data);
export const updateAppointmentStatus = (id, status) => api.put(`/admin/appointments/${id}/status`, { status }).then(r => r.data);
export const requestAdminReschedule = (id, data) => api.post(`/admin/appointments/${id}/reschedule`, data).then(r => r.data);
export const getSettings = () => api.get('/admin/settings').then(r => r.data);
export const updateSettings = (data) => api.put('/admin/settings', data).then(r => r.data);
export const getWorkersCalendar = (year, month) => api.get('/admin/workers-calendar', { params: { year, month } }).then(r => r.data);
export const getWorkersDayDetail = (date) => api.get('/admin/workers-calendar/day', { params: { date } }).then(r => r.data);
export const toggleAdminAsWorker = () => api.patch('/admin/me/worker-toggle').then(r => r.data);
export const getCustomers = () => api.get('/admin/customers').then(r => r.data);
export const getCustomerDetail = (id) => api.get(`/admin/customers/${id}`).then(r => r.data);
export const updateCustomerNotes = (id, notes) => api.put(`/admin/customers/${id}/notes`, { notes }).then(r => r.data);
export const completeOnboarding = () => api.post('/admin/onboarding/complete').then(r => r.data);
export const getAnalytics = () => api.get('/admin/analytics').then(r => r.data);
export const sendAiMessage = (messages) => api.post('/admin/ai-chat', { messages }).then(r => r.data);
export const getCategories = () => api.get('/admin/categories').then(r => r.data);
export const createCategory = (data) => api.post('/admin/categories', data).then(r => r.data);
export const updateCategory = (id, data) => api.put(`/admin/categories/${id}`, data).then(r => r.data);
export const deleteCategory = (id) => api.delete(`/admin/categories/${id}`).then(r => r.data);
export const getStore = () => api.get('/admin/store').then(r => r.data);
export const toggleStore = () => api.post('/admin/store/toggle').then(r => r.data);
export const createProduct = (data) => api.post('/admin/store/products', data).then(r => r.data);
export const updateProduct = (id, data) => api.put(`/admin/store/products/${id}`, data).then(r => r.data);
export const deleteProduct = (id) => api.delete(`/admin/store/products/${id}`).then(r => r.data);
export const getRecurringRules = () => api.get('/admin/recurring-rules').then(r => r.data);
export const createRecurringRule = (data) => api.post('/admin/recurring-rules', data).then(r => r.data);
export const updateRecurringRule = (id, data) => api.put(`/admin/recurring-rules/${id}`, data).then(r => r.data);
export const deleteRecurringRule = (id) => api.delete(`/admin/recurring-rules/${id}`).then(r => r.data);
export const getCalendarStatus = () => api.get('/admin/me/calendar-status').then(r => r.data);
export const disconnectCalendar = () => api.post('/admin/me/calendar-disconnect').then(r => r.data);
export const uploadImage = (file) => {
  const form = new FormData();
  form.append('image', file);
  return api.post('/admin/upload', form, { headers: { 'Content-Type': 'multipart/form-data' } }).then(r => r.data);
};
